name: check lint

# Controls when the action will run. Triggers the workflow on pull request
on:
  pull_request:
    branches: [ main, release, check ]

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
  
      - name: Check frontend
        run: |
          npm install
          npm run lint-styles
          npm run lint-js
